/*
 * artiFlow REST API Definition
 *
 * artiFlow REST API Definition
 *
 * API version: 1.0.0
 * Contact: privet56@hotmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package flowrestapitypes

import (
	"time"
)

//Configuration type for the rest api
type Configuration struct {
	Name string `json:"name"`

	Time time.Time `json:"time"`

	RequestURL string `json:"requestURL"`

	Entries []ConfigurationEntry `json:"entries"`
}
